### ISSUE TITLE
Add dynamic route for categories

### ISSUE THREAD

**Issue by decrek** [LarsBreuren/progressive-web-apps-1920#3]
You could move all dynamic routes into one route. So instead of `app.get('/people')` and `app.get('/vehicles')` move them to `app.get('/:category')`. You could do the same for all nested routes, like you do already here: https://github.com/LarsBreuren/progressive-web-apps-1920/blob/4a88d8992efa469b41406f86b60ccec2d3a0599e/index.js#L132.
But this route is not matched on `/people/aapje` since above the dynamic route is already a more specific `/people/:id` route.

**Comment by LarsBreuren** [comment]
Done! Thanks for the feedback :)
